CREATE TYPE variant_summary AS (
	call_rate REAL,
	maf REAL,
	subset1_call_rate REAL,
	subset1_maf REAL,
	subset2_call_rate REAL,
	subset2_maf REAL
);

CREATE OR REPLACE FUNCTION summarize_variant( TINYINT[], INTEGER[] DEFAULT NULL, INTEGER[] DEFAULT NULL )
	RETURNS variant_summary
	AS 'MODULE_PATHNAME'
	LANGUAGE C IMMUTABLE PARALLEL SAFE COST 10000;

CREATE OR REPLACE FUNCTION alternate_allele_frequency( TINYINT[], INTEGER[] )
	RETURNS REAL
	AS 'MODULE_PATHNAME'
	LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE COST 10000;
